# Generated by Django 5.0.2 on 2024-05-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_categoty_car_description_car_is_sold_alter_car_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
    ]
