# Generated by Django 5.0.2 on 2024-05-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_cardetail_car_height_car_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='height',
        ),
        migrations.RemoveField(
            model_name='car',
            name='width',
        ),
    ]
