# Generated by Django 5.0.2 on 2024-05-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_height_car_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='car',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
