# Generated by Django 5.0.2 on 2024-05-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_car_height_remove_car_width'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarDetail',
        ),
    ]
