# Generated by Django 5.0.2 on 2024-05-01 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_delete_cardetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='cars.car')),
                ('color', models.CharField(default='#FFFFFF', max_length=20)),
                ('engine_type', models.CharField(max_length=15)),
                ('engine_capacity', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveBigIntegerField()),
                ('gearbox_type', models.CharField(max_length=15)),
                ('number_of_doors', models.PositiveSmallIntegerField()),
                ('power', models.PositiveSmallIntegerField()),
                ('top_speed', models.PositiveSmallIntegerField()),
                ('acceleration', models.PositiveSmallIntegerField()),
                ('fuel_consumption', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='car',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
