# Generated by Django 5.0.2 on 2024-05-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_cardetail_car_height_car_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='acceleration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='engine_capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='engine_type',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='fuel_consumption',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='gearbox_type',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='mileage',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='number_of_doors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='power',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='top_speed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
