# Generated by Django 5.0.2 on 2024-05-01 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0014_remove_car_category_remove_cardetail_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=55)),
                ('model', models.CharField(max_length=55)),
                ('description', models.TextField(default=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars_images/')),
                ('year', models.IntegerField()),
                ('price', models.FloatField()),
                ('is_sold', models.BooleanField(default=False)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='cars.car')),
                ('color', models.CharField(default='#FFFFFF', max_length=20)),
                ('engine_type', models.CharField(default=None, max_length=15)),
                ('engine_capacity', models.PositiveSmallIntegerField(default=0)),
                ('mileage', models.PositiveBigIntegerField(default=0)),
                ('gearbox_type', models.CharField(default=0, max_length=15)),
                ('number_of_doors', models.PositiveSmallIntegerField(default=0)),
                ('power', models.PositiveSmallIntegerField(default=0)),
                ('top_speed', models.PositiveSmallIntegerField(default=0)),
                ('acceleration', models.PositiveSmallIntegerField(default=0)),
                ('fuel_consumption', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.category'),
        ),
    ]
