# Generated by Django 5.0.2 on 2024-05-01 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_remove_car_category_category_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.category'),
        ),
    ]
