# Generated by Django 5.0.2 on 2024-05-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
