# Generated by Django 5.0.2 on 2024-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
